# Generated by Django 3.1.4 on 2021-03-20 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('compagnie', models.CharField(max_length=255, null=True)),
                ('nom', models.CharField(max_length=255, null=True)),
                ('dateDebut', models.DateTimeField(auto_now_add=True)),
                ('dateFin', models.DateTimeField(auto_now_add=True)),
                ('projetNum', models.CharField(max_length=100, null=True)),
                ('notes', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormCovid',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255, null=True)),
                ('compagnie', models.CharField(max_length=255, null=True)),
                ('nom', models.CharField(max_length=255, null=True)),
                ('dateEntre', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('projet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mgc.projet')),
            ],
        ),
    ]
